language: rust
cache: cargo

email:
  recipients:
    - stephen.gutekanst@gmail.com
  on_success: always # default: change
  on_failure: always # default: always

script:
  - TARGET=x86_64-unknown-linux-musl cargo build --release

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    echo "pwd" && pwd;
    echo "ls" && ls;
    echo "ls target/" && ls target/;
    echo "ls release/" && ls release/;
    echo "ls target/x86_64-unknown-linux-musl" && ls target/x86_64-unknown-linux-musl;
    docker build -t "sourcegraph/syntect_server:ci" .;
    docker push "sourcegraph/syntect_server:ci";
    fi

matrix:
  include:
    - os: linux
      rust: nightly
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - musl
            - musl-dev
            - musl-tools
