language: rust
email:
  recipients:
    - stephen.gutekanst@gmail.com
  on_success: change # default: change
  on_failure: change # default: always
rust:
  - nightly
script:
  - cargo build --release
