language: rust
cache: cargo

email:
  recipients:
    - stephen.gutekanst@gmail.com
  on_success: always # default: change
  on_failure: always # default: always

script:
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
  - rustup target add x86_64-unknown-linux-musl
  - cargo build --release --target x86_64-unknown-linux-musl

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t "sourcegraph/syntect_server:ci" .;
    docker push "sourcegraph/syntect_server:ci";
    fi

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - musl
            - musl-dev
            - musl-tools
