name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t sourcegraph/syntax_highlighter:$(date +"%y-%m-%d")_$(git log -n1 --pretty=format:%h)
    - name: Push the Docker image
      run: docker push sourcegraph/syntax_highlighter:$(date +"%y-%m-%d")_$(git log -n1 --pretty=format:%h)
